### ISSUE TITLE
MindRaider doesn't work with Java 7 (@sf.net) > Release 15.0 

### ISSUE THREAD

**Issue by intuser** [dvorka/mindraider#20]
From java 7 on mindraider doesn't run. It only shows the splash-screen and than gives the following error:

Exception in thread "main" java.lang.IllegalStateException: This function should be called while holding treeLock
        at java.awt.Component.checkTreeLock(Component.java:1200)
        at java.awt.Container.validateTree(Container.java:1682)
        at com.mindcognition.mindraider.ui.swing.explorer.ExplorerJPanel.<init>(ExplorerJPanel.java:131)
        at com.mindcognition.mindraider.ui.swing.explorer.ExplorerJPanel.getInstance(ExplorerJPanel.java:136)
        at com.emental.mindraider.ui.frames.MindRaiderMainWindow.<init>(MindRaiderMainWindow.java:171)
        at com.emental.mindraider.ui.frames.MindRaiderMainWindow.getInstance(MindRaiderMainWindow.java:120)
        at com.mindcognition.mindraider.MindRaiderApplication.main(MindRaiderApplication.java:237)
        at MindRaiderRunner.main(MindRaiderRunner.java:53)

I'm using debian which doesn't provide java 6 with its current stable release (jessie).

**Comment by dvorka** [comment]
This bug has been fixed in Git repository by commit https://github.com/dvorka/mindraider/commit/f409ae47f316e61a94eb17e68a6e5f57a9c4b4cd
but it is not released yet. Which distribution you use? Please can you give a try to: https://github.com/dvorka/mindraider/releases/tag/v15.0

**Comment by intuser** [comment]
I use debian 8.0 (jessie) and mindraider 8.0. [Java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)]

I tried v 15.0 but unfortunatelly I get:

Exception in thread "main" java.lang.NoClassDefFoundError: com/mindcognition/mindraider/MindRaiderApplication
        at MindRaiderRunner.main(MindRaiderRunner.java:53)
Caused by: java.lang.ClassNotFoundException: com.mindcognition.mindraider.MindRaiderApplication
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more

**Comment by dvorka** [comment]
My apologies - I found the bug in a JAR used to start the application. Please download distribution once more OR download `run.jar` only https://github.com/dvorka/mindraider/releases/download/v15.0/run.jar and place it to the root (rewrite existing file).

**Comment by dvorka** [comment]
JAR fixed, distros re-uploaded.

**Comment by intuser** [comment]
Thanks. Now it works.

**Comment by dvorka** [comment]
:+1:
